### ISSUE TITLE
ps-container doesn't seem to be working as intended

### ISSUE THREAD

**Issue by Sharondio** [dpiccone/ng-pageslide#128]
It's my understanding that ps-container tells the slide what element to attach to, allowing slides within other elements other than body. It's not working this way. I noticed there was an update to line 111, but it seems even the old code wasn't working. However, setting the slider.style.position to 'relative' does work. Please advise.

https://plnkr.co/edit/k6eSEmFrp4Qt1vsN4FQH?p=preview (with line 111 updated in angular-slider-directive.js)

**Comment by dpiccone** [comment]
> It's my understanding that ps-container tells the slide what element to attach to

Yes, however, your code works because your are forcing the overflow-x to be hidden. 

I changed the behaviour recently and forced the positioning to be fixed because while ps-container tells the slide which node to attach itself too, the slider itself should not be contained in that.
That is because the main use of this directive should be to have a sliding panel off the screen, which means that visually the container should always be the screen.

**Comment by Sharondio** [comment]
So then what is the purpose of letting someone attach to a different element? Seems like adding complexity for no real gain.

**Comment by dpiccone** [comment]
This behaviour was introduced in an early PR which was working only in some cases (eg when having a relative positioned div and a hidden overflow), it is deprecated and should be removed from the api.

**Comment by Sharondio** [comment]
Unfortunately, that's my use case so I'll move forward with either a fork or another solution. Thank you!

**Comment by dpiccone** [comment]
Unfortunately the feature had some problems also in v1, as soon as I find some time I'll make some proper examples and reintroduce it within more restrictive conditions on the container. If you feel to fork and contribute you are welcome :)
