### ISSUE TITLE
"on open" callback

### ISSUE THREAD

**Issue by thedriblet** [dpiccone/ng-pageslide#70]
As a developer I would like to provide a callback that executes once the slider is open and uncloaked so that I can set the focus on an input inside the slider.

So far I've only found one workaround with the current version: the caller has to watch the "open" variable, set a timeout that runs after param.speed * 1000 (the time it takes for the cloak to be removed), then set the focus. Although this works, it seems brittle.

I'm not having much luck with a focus directive, since the element apparently renders while it's still in display: none. If the slider were changed to opacity: 0 instead of display: none, it works the first time, but not if one were to close and re-open the slider (without an additional ngIf). I also tried watching the "display: block" style on the "content" element without success.

A callback that executes after the slider is opened and the cloak is removed seems like it might offer a relatively clean and straightforward solution.

**Comment by dpiccone** [comment]
I agree, it  truly makes sense to have callbacks for open/close logic.

Since all is based on css3 transition it should be hooked on transition end.
Event listeners should follow vendor prefixes.

element.addEventListener("webkitAnimationEnd", callfunction,false);
element.addEventListener("animationend", callfunction,false);
element.addEventListener("oanimationend", callfunction,false);

**Comment by deeg** [comment]
+1 would like to see this enhancement.

**Comment by dpiccone** [comment]
https://github.com/dpiccone/ng-pageslide/commit/45b02f2f08a8a0261728c1f94c6d697dddd10cbe

You can now use onclose onopen callbacks which fire at the end of the transition.
To fire a callback at the beginning should be sufficient to watch the psOpen switch and react to it.
