### ISSUE TITLE
Option for ps-cloak to not squeeze content

### ISSUE THREAD

**Issue by guikubivan** [dpiccone/ng-pageslide#88]
It's a bit distracting to see the content changing as the slide out appears, but it's still useful to see the animation. Would love to see an option so that the content doesn't do that.

**Comment by dpiccone** [comment]
This has been removed in v1.1 the content is always hidden until the slider is open now

**Comment by charleshimmer** [comment]
If the left or right position property is what is used to control if the panel is open or closed instead of panel's width, the content wouldn't be squished but rather would slide with the panel smoothly.  I find having a blank panel slide in and then content pop in is distracting.  See how materialize css does it: http://materializecss.com/side-nav.html

**Comment by dpiccone** [comment]
Originally it was like that, but that assumes the panel to be attached to the body or the outer container having hidden overflow, hence the switch, which I don't like to depend on.

**Comment by charleshimmer** [comment]
Gotcha.
